site_name: Gospotlib
repo_url: https://github.com/timvosch/gospotlib
repo_name: timvosch/gospotlib
theme:
  name: material
  font:
    text: Roboto Condensed
  features:
    - navigation.sections
  icon:
    repo: fontawesome/brands/git-alt 
  palette:
    - scheme: default
      primary: light blue
      accent: blue grey
extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - getting-started/introduction.md
  - getting-started/packages.md
  - Contributing:
    - contributing/development.md
  - Spotify:
    - spotify/overview.md
