// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: ad-hermes-proxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     *string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Times    *uint32 `protobuf:"varint,2,opt,name=times" json:"times,omitempty"`
	Interval *uint64 `protobuf:"varint,3,opt,name=interval" json:"interval,omitempty"`
}

func (x *Rule) Reset() {
	*x = Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_hermes_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_ad_hermes_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_ad_hermes_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Rule) GetTimes() uint32 {
	if x != nil && x.Times != nil {
		return *x.Times
	}
	return 0
}

func (x *Rule) GetInterval() uint64 {
	if x != nil && x.Interval != nil {
		return *x.Interval
	}
	return 0
}

type AdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientLanguage *string  `protobuf:"bytes,1,opt,name=client_language,json=clientLanguage" json:"client_language,omitempty"`
	Product        *string  `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
	Version        *uint32  `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Type           *string  `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	AvoidAds       []string `protobuf:"bytes,5,rep,name=avoidAds" json:"avoidAds,omitempty"`
}

func (x *AdRequest) Reset() {
	*x = AdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_hermes_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdRequest) ProtoMessage() {}

func (x *AdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_hermes_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdRequest.ProtoReflect.Descriptor instead.
func (*AdRequest) Descriptor() ([]byte, []int) {
	return file_ad_hermes_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *AdRequest) GetClientLanguage() string {
	if x != nil && x.ClientLanguage != nil {
		return *x.ClientLanguage
	}
	return ""
}

func (x *AdRequest) GetProduct() string {
	if x != nil && x.Product != nil {
		return *x.Product
	}
	return ""
}

func (x *AdRequest) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *AdRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *AdRequest) GetAvoidAds() []string {
	if x != nil {
		return x.AvoidAds
	}
	return nil
}

type AdQueueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdQueueEntry []*AdQueueEntry `protobuf:"bytes,1,rep,name=adQueueEntry" json:"adQueueEntry,omitempty"`
}

func (x *AdQueueResponse) Reset() {
	*x = AdQueueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_hermes_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdQueueResponse) ProtoMessage() {}

func (x *AdQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_hermes_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdQueueResponse.ProtoReflect.Descriptor instead.
func (*AdQueueResponse) Descriptor() ([]byte, []int) {
	return file_ad_hermes_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *AdQueueResponse) GetAdQueueEntry() []*AdQueueEntry {
	if x != nil {
		return x.AdQueueEntry
	}
	return nil
}

type AdFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Format *string `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
}

func (x *AdFile) Reset() {
	*x = AdFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_hermes_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdFile) ProtoMessage() {}

func (x *AdFile) ProtoReflect() protoreflect.Message {
	mi := &file_ad_hermes_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdFile.ProtoReflect.Descriptor instead.
func (*AdFile) Descriptor() ([]byte, []int) {
	return file_ad_hermes_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *AdFile) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *AdFile) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

type AdQueueEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime       *uint64   `protobuf:"varint,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime         *uint64   `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	Priority        *float64  `protobuf:"fixed64,3,opt,name=priority" json:"priority,omitempty"`
	Token           *string   `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	AdVersion       *uint32   `protobuf:"varint,5,opt,name=ad_version,json=adVersion" json:"ad_version,omitempty"`
	Id              *string   `protobuf:"bytes,6,opt,name=id" json:"id,omitempty"`
	Type            *string   `protobuf:"bytes,7,opt,name=type" json:"type,omitempty"`
	Campaign        *string   `protobuf:"bytes,8,opt,name=campaign" json:"campaign,omitempty"`
	Advertiser      *string   `protobuf:"bytes,9,opt,name=advertiser" json:"advertiser,omitempty"`
	Url             *string   `protobuf:"bytes,10,opt,name=url" json:"url,omitempty"`
	Duration        *uint64   `protobuf:"varint,11,opt,name=duration" json:"duration,omitempty"`
	Expiry          *uint64   `protobuf:"varint,12,opt,name=expiry" json:"expiry,omitempty"`
	TrackingUrl     *string   `protobuf:"bytes,13,opt,name=tracking_url,json=trackingUrl" json:"tracking_url,omitempty"`
	BannerType      *string   `protobuf:"bytes,14,opt,name=banner_type,json=bannerType" json:"banner_type,omitempty"`
	Html            *string   `protobuf:"bytes,15,opt,name=html" json:"html,omitempty"`
	Image           *string   `protobuf:"bytes,16,opt,name=image" json:"image,omitempty"`
	BackgroundImage *string   `protobuf:"bytes,17,opt,name=background_image,json=backgroundImage" json:"background_image,omitempty"`
	BackgroundUrl   *string   `protobuf:"bytes,18,opt,name=background_url,json=backgroundUrl" json:"background_url,omitempty"`
	BackgroundColor *string   `protobuf:"bytes,19,opt,name=background_color,json=backgroundColor" json:"background_color,omitempty"`
	Title           *string   `protobuf:"bytes,20,opt,name=title" json:"title,omitempty"`
	Caption         *string   `protobuf:"bytes,21,opt,name=caption" json:"caption,omitempty"`
	File            []*AdFile `protobuf:"bytes,22,rep,name=file" json:"file,omitempty"`
	Rule            []*Rule   `protobuf:"bytes,23,rep,name=rule" json:"rule,omitempty"`
}

func (x *AdQueueEntry) Reset() {
	*x = AdQueueEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_hermes_proxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdQueueEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdQueueEntry) ProtoMessage() {}

func (x *AdQueueEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ad_hermes_proxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdQueueEntry.ProtoReflect.Descriptor instead.
func (*AdQueueEntry) Descriptor() ([]byte, []int) {
	return file_ad_hermes_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *AdQueueEntry) GetStartTime() uint64 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *AdQueueEntry) GetEndTime() uint64 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

func (x *AdQueueEntry) GetPriority() float64 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *AdQueueEntry) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *AdQueueEntry) GetAdVersion() uint32 {
	if x != nil && x.AdVersion != nil {
		return *x.AdVersion
	}
	return 0
}

func (x *AdQueueEntry) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *AdQueueEntry) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *AdQueueEntry) GetCampaign() string {
	if x != nil && x.Campaign != nil {
		return *x.Campaign
	}
	return ""
}

func (x *AdQueueEntry) GetAdvertiser() string {
	if x != nil && x.Advertiser != nil {
		return *x.Advertiser
	}
	return ""
}

func (x *AdQueueEntry) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *AdQueueEntry) GetDuration() uint64 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *AdQueueEntry) GetExpiry() uint64 {
	if x != nil && x.Expiry != nil {
		return *x.Expiry
	}
	return 0
}

func (x *AdQueueEntry) GetTrackingUrl() string {
	if x != nil && x.TrackingUrl != nil {
		return *x.TrackingUrl
	}
	return ""
}

func (x *AdQueueEntry) GetBannerType() string {
	if x != nil && x.BannerType != nil {
		return *x.BannerType
	}
	return ""
}

func (x *AdQueueEntry) GetHtml() string {
	if x != nil && x.Html != nil {
		return *x.Html
	}
	return ""
}

func (x *AdQueueEntry) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *AdQueueEntry) GetBackgroundImage() string {
	if x != nil && x.BackgroundImage != nil {
		return *x.BackgroundImage
	}
	return ""
}

func (x *AdQueueEntry) GetBackgroundUrl() string {
	if x != nil && x.BackgroundUrl != nil {
		return *x.BackgroundUrl
	}
	return ""
}

func (x *AdQueueEntry) GetBackgroundColor() string {
	if x != nil && x.BackgroundColor != nil {
		return *x.BackgroundColor
	}
	return ""
}

func (x *AdQueueEntry) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *AdQueueEntry) GetCaption() string {
	if x != nil && x.Caption != nil {
		return *x.Caption
	}
	return ""
}

func (x *AdQueueEntry) GetFile() []*AdFile {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *AdQueueEntry) GetRule() []*Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

var File_ad_hermes_proxy_proto protoreflect.FileDescriptor

var file_ad_hermes_proxy_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x64, 0x2d, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x4c, 0x0a, 0x04, 0x52,
	0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x98, 0x01, 0x0a, 0x09, 0x41, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x76, 0x6f, 0x69,
	0x64, 0x41, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61, 0x76, 0x6f, 0x69,
	0x64, 0x41, 0x64, 0x73, 0x22, 0x47, 0x0a, 0x0f, 0x41, 0x64, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x61, 0x64, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x41, 0x64, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0c, 0x61, 0x64, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x30, 0x0a,
	0x06, 0x41, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22,
	0x98, 0x05, 0x0a, 0x0c, 0x41, 0x64, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x61, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x79, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x55, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x29, 0x0a, 0x10, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x62, 0x61, 0x63, 0x6b, 0x67,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x61,
	0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x12, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x72,
	0x6c, 0x12, 0x29, 0x0a, 0x10, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x62, 0x61, 0x63,
	0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x15, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x16, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x04,
	0x72, 0x75, 0x6c, 0x65, 0x18, 0x17, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x75, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62,
}

var (
	file_ad_hermes_proxy_proto_rawDescOnce sync.Once
	file_ad_hermes_proxy_proto_rawDescData = file_ad_hermes_proxy_proto_rawDesc
)

func file_ad_hermes_proxy_proto_rawDescGZIP() []byte {
	file_ad_hermes_proxy_proto_rawDescOnce.Do(func() {
		file_ad_hermes_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_ad_hermes_proxy_proto_rawDescData)
	})
	return file_ad_hermes_proxy_proto_rawDescData
}

var file_ad_hermes_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ad_hermes_proxy_proto_goTypes = []interface{}{
	(*Rule)(nil),            // 0: pb.Rule
	(*AdRequest)(nil),       // 1: pb.AdRequest
	(*AdQueueResponse)(nil), // 2: pb.AdQueueResponse
	(*AdFile)(nil),          // 3: pb.AdFile
	(*AdQueueEntry)(nil),    // 4: pb.AdQueueEntry
}
var file_ad_hermes_proxy_proto_depIdxs = []int32{
	4, // 0: pb.AdQueueResponse.adQueueEntry:type_name -> pb.AdQueueEntry
	3, // 1: pb.AdQueueEntry.file:type_name -> pb.AdFile
	0, // 2: pb.AdQueueEntry.rule:type_name -> pb.Rule
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ad_hermes_proxy_proto_init() }
func file_ad_hermes_proxy_proto_init() {
	if File_ad_hermes_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ad_hermes_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_hermes_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_hermes_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdQueueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_hermes_proxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_hermes_proxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdQueueEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ad_hermes_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ad_hermes_proxy_proto_goTypes,
		DependencyIndexes: file_ad_hermes_proxy_proto_depIdxs,
		MessageInfos:      file_ad_hermes_proxy_proto_msgTypes,
	}.Build()
	File_ad_hermes_proxy_proto = out.File
	file_ad_hermes_proxy_proto_rawDesc = nil
	file_ad_hermes_proxy_proto_goTypes = nil
	file_ad_hermes_proxy_proto_depIdxs = nil
}
