// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: playlist4meta.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadFormat_Codec int32

const (
	DownloadFormat_CODEC_UNKNOWN  DownloadFormat_Codec = 0
	DownloadFormat_OGG_VORBIS     DownloadFormat_Codec = 1
	DownloadFormat_FLAC           DownloadFormat_Codec = 2
	DownloadFormat_MPEG_1_LAYER_3 DownloadFormat_Codec = 3
)

// Enum value maps for DownloadFormat_Codec.
var (
	DownloadFormat_Codec_name = map[int32]string{
		0: "CODEC_UNKNOWN",
		1: "OGG_VORBIS",
		2: "FLAC",
		3: "MPEG_1_LAYER_3",
	}
	DownloadFormat_Codec_value = map[string]int32{
		"CODEC_UNKNOWN":  0,
		"OGG_VORBIS":     1,
		"FLAC":           2,
		"MPEG_1_LAYER_3": 3,
	}
)

func (x DownloadFormat_Codec) Enum() *DownloadFormat_Codec {
	p := new(DownloadFormat_Codec)
	*p = x
	return p
}

func (x DownloadFormat_Codec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DownloadFormat_Codec) Descriptor() protoreflect.EnumDescriptor {
	return file_playlist4meta_proto_enumTypes[0].Descriptor()
}

func (DownloadFormat_Codec) Type() protoreflect.EnumType {
	return &file_playlist4meta_proto_enumTypes[0]
}

func (x DownloadFormat_Codec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DownloadFormat_Codec) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DownloadFormat_Codec(num)
	return nil
}

// Deprecated: Use DownloadFormat_Codec.Descriptor instead.
func (DownloadFormat_Codec) EnumDescriptor() ([]byte, []int) {
	return file_playlist4meta_proto_rawDescGZIP(), []int{1, 0}
}

type ListChecksum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version *int32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Sha1    []byte `protobuf:"bytes,4,opt,name=sha1" json:"sha1,omitempty"`
}

func (x *ListChecksum) Reset() {
	*x = ListChecksum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playlist4meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChecksum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChecksum) ProtoMessage() {}

func (x *ListChecksum) ProtoReflect() protoreflect.Message {
	mi := &file_playlist4meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChecksum.ProtoReflect.Descriptor instead.
func (*ListChecksum) Descriptor() ([]byte, []int) {
	return file_playlist4meta_proto_rawDescGZIP(), []int{0}
}

func (x *ListChecksum) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *ListChecksum) GetSha1() []byte {
	if x != nil {
		return x.Sha1
	}
	return nil
}

type DownloadFormat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codec *DownloadFormat_Codec `protobuf:"varint,1,opt,name=codec,enum=pb.DownloadFormat_Codec" json:"codec,omitempty"`
}

func (x *DownloadFormat) Reset() {
	*x = DownloadFormat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playlist4meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFormat) ProtoMessage() {}

func (x *DownloadFormat) ProtoReflect() protoreflect.Message {
	mi := &file_playlist4meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFormat.ProtoReflect.Descriptor instead.
func (*DownloadFormat) Descriptor() ([]byte, []int) {
	return file_playlist4meta_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadFormat) GetCodec() DownloadFormat_Codec {
	if x != nil && x.Codec != nil {
		return *x.Codec
	}
	return DownloadFormat_CODEC_UNKNOWN
}

type ListAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                    *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description             *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Picture                 []byte  `protobuf:"bytes,3,opt,name=picture" json:"picture,omitempty"`
	Collaborative           *bool   `protobuf:"varint,4,opt,name=collaborative" json:"collaborative,omitempty"`
	Pl3Version              *string `protobuf:"bytes,5,opt,name=pl3_version,json=pl3Version" json:"pl3_version,omitempty"`
	DeletedByOwner          *bool   `protobuf:"varint,6,opt,name=deleted_by_owner,json=deletedByOwner" json:"deleted_by_owner,omitempty"`
	RestrictedCollaborative *bool   `protobuf:"varint,7,opt,name=restricted_collaborative,json=restrictedCollaborative" json:"restricted_collaborative,omitempty"`
	DeprecatedClientId      *int64  `protobuf:"varint,8,opt,name=deprecated_client_id,json=deprecatedClientId" json:"deprecated_client_id,omitempty"`
	PublicStarred           *bool   `protobuf:"varint,9,opt,name=public_starred,json=publicStarred" json:"public_starred,omitempty"`
	ClientId                *string `protobuf:"bytes,10,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
}

func (x *ListAttributes) Reset() {
	*x = ListAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playlist4meta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributes) ProtoMessage() {}

func (x *ListAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_playlist4meta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributes.ProtoReflect.Descriptor instead.
func (*ListAttributes) Descriptor() ([]byte, []int) {
	return file_playlist4meta_proto_rawDescGZIP(), []int{2}
}

func (x *ListAttributes) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListAttributes) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ListAttributes) GetPicture() []byte {
	if x != nil {
		return x.Picture
	}
	return nil
}

func (x *ListAttributes) GetCollaborative() bool {
	if x != nil && x.Collaborative != nil {
		return *x.Collaborative
	}
	return false
}

func (x *ListAttributes) GetPl3Version() string {
	if x != nil && x.Pl3Version != nil {
		return *x.Pl3Version
	}
	return ""
}

func (x *ListAttributes) GetDeletedByOwner() bool {
	if x != nil && x.DeletedByOwner != nil {
		return *x.DeletedByOwner
	}
	return false
}

func (x *ListAttributes) GetRestrictedCollaborative() bool {
	if x != nil && x.RestrictedCollaborative != nil {
		return *x.RestrictedCollaborative
	}
	return false
}

func (x *ListAttributes) GetDeprecatedClientId() int64 {
	if x != nil && x.DeprecatedClientId != nil {
		return *x.DeprecatedClientId
	}
	return 0
}

func (x *ListAttributes) GetPublicStarred() bool {
	if x != nil && x.PublicStarred != nil {
		return *x.PublicStarred
	}
	return false
}

func (x *ListAttributes) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

type ItemAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddedBy          *string         `protobuf:"bytes,1,opt,name=added_by,json=addedBy" json:"added_by,omitempty"`
	Timestamp        *int64          `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Message          *string         `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Seen             *bool           `protobuf:"varint,4,opt,name=seen" json:"seen,omitempty"`
	DownloadCount    *int64          `protobuf:"varint,5,opt,name=download_count,json=downloadCount" json:"download_count,omitempty"`
	DownloadFormat   *DownloadFormat `protobuf:"bytes,6,opt,name=download_format,json=downloadFormat" json:"download_format,omitempty"`
	SevendigitalId   *string         `protobuf:"bytes,7,opt,name=sevendigital_id,json=sevendigitalId" json:"sevendigital_id,omitempty"`
	SevendigitalLeft *int64          `protobuf:"varint,8,opt,name=sevendigital_left,json=sevendigitalLeft" json:"sevendigital_left,omitempty"`
	SeenAt           *int64          `protobuf:"varint,9,opt,name=seen_at,json=seenAt" json:"seen_at,omitempty"`
	Public           *bool           `protobuf:"varint,10,opt,name=public" json:"public,omitempty"`
}

func (x *ItemAttributes) Reset() {
	*x = ItemAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playlist4meta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAttributes) ProtoMessage() {}

func (x *ItemAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_playlist4meta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAttributes.ProtoReflect.Descriptor instead.
func (*ItemAttributes) Descriptor() ([]byte, []int) {
	return file_playlist4meta_proto_rawDescGZIP(), []int{3}
}

func (x *ItemAttributes) GetAddedBy() string {
	if x != nil && x.AddedBy != nil {
		return *x.AddedBy
	}
	return ""
}

func (x *ItemAttributes) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *ItemAttributes) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ItemAttributes) GetSeen() bool {
	if x != nil && x.Seen != nil {
		return *x.Seen
	}
	return false
}

func (x *ItemAttributes) GetDownloadCount() int64 {
	if x != nil && x.DownloadCount != nil {
		return *x.DownloadCount
	}
	return 0
}

func (x *ItemAttributes) GetDownloadFormat() *DownloadFormat {
	if x != nil {
		return x.DownloadFormat
	}
	return nil
}

func (x *ItemAttributes) GetSevendigitalId() string {
	if x != nil && x.SevendigitalId != nil {
		return *x.SevendigitalId
	}
	return ""
}

func (x *ItemAttributes) GetSevendigitalLeft() int64 {
	if x != nil && x.SevendigitalLeft != nil {
		return *x.SevendigitalLeft
	}
	return 0
}

func (x *ItemAttributes) GetSeenAt() int64 {
	if x != nil && x.SeenAt != nil {
		return *x.SeenAt
	}
	return 0
}

func (x *ItemAttributes) GetPublic() bool {
	if x != nil && x.Public != nil {
		return *x.Public
	}
	return false
}

type StringAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (x *StringAttribute) Reset() {
	*x = StringAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playlist4meta_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringAttribute) ProtoMessage() {}

func (x *StringAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_playlist4meta_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringAttribute.ProtoReflect.Descriptor instead.
func (*StringAttribute) Descriptor() ([]byte, []int) {
	return file_playlist4meta_proto_rawDescGZIP(), []int{4}
}

func (x *StringAttribute) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *StringAttribute) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type StringAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attribute []*StringAttribute `protobuf:"bytes,1,rep,name=attribute" json:"attribute,omitempty"`
}

func (x *StringAttributes) Reset() {
	*x = StringAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playlist4meta_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringAttributes) ProtoMessage() {}

func (x *StringAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_playlist4meta_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringAttributes.ProtoReflect.Descriptor instead.
func (*StringAttributes) Descriptor() ([]byte, []int) {
	return file_playlist4meta_proto_rawDescGZIP(), []int{5}
}

func (x *StringAttributes) GetAttribute() []*StringAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

var File_playlist4meta_proto protoreflect.FileDescriptor

var file_playlist4meta_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x34, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3c, 0x0a, 0x0c, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x68, 0x61, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x73, 0x68, 0x61, 0x31, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x2e, 0x0a, 0x05, 0x63, 0x6f,
	0x64, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x43, 0x6f,
	0x64, 0x65, 0x63, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x22, 0x48, 0x0a, 0x05, 0x43, 0x6f,
	0x64, 0x65, 0x63, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4f, 0x44, 0x45, 0x43, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x47, 0x47, 0x5f, 0x56, 0x4f,
	0x52, 0x42, 0x49, 0x53, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x4c, 0x41, 0x43, 0x10, 0x02,
	0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x50, 0x45, 0x47, 0x5f, 0x31, 0x5f, 0x4c, 0x41, 0x59, 0x45, 0x52,
	0x5f, 0x33, 0x10, 0x03, 0x22, 0x82, 0x03, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x61,
	0x62, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x70, 0x6c, 0x33, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x33, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x28,
	0x0a, 0x10, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x5f, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x18, 0x72, 0x65, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x17, 0x72, 0x65, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74,
	0x69, 0x76, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x12, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x73, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0xe2, 0x02, 0x0a, 0x0e, 0x49, 0x74,
	0x65, 0x6d, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x64, 0x64, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73,
	0x65, 0x65, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x64, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x0f, 0x64, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x0e, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x76, 0x65, 0x6e,
	0x64, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x64, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x49, 0x64,
	0x12, 0x2b, 0x0a, 0x11, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x64, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c,
	0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x73, 0x65, 0x76,
	0x65, 0x6e, 0x64, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x73, 0x65, 0x65, 0x6e, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x65, 0x65, 0x6e, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x22, 0x39,
	0x0a, 0x0f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x45, 0x0a, 0x10, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x31, 0x0a,
	0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62,
}

var (
	file_playlist4meta_proto_rawDescOnce sync.Once
	file_playlist4meta_proto_rawDescData = file_playlist4meta_proto_rawDesc
)

func file_playlist4meta_proto_rawDescGZIP() []byte {
	file_playlist4meta_proto_rawDescOnce.Do(func() {
		file_playlist4meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_playlist4meta_proto_rawDescData)
	})
	return file_playlist4meta_proto_rawDescData
}

var file_playlist4meta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_playlist4meta_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_playlist4meta_proto_goTypes = []interface{}{
	(DownloadFormat_Codec)(0), // 0: pb.DownloadFormat.Codec
	(*ListChecksum)(nil),      // 1: pb.ListChecksum
	(*DownloadFormat)(nil),    // 2: pb.DownloadFormat
	(*ListAttributes)(nil),    // 3: pb.ListAttributes
	(*ItemAttributes)(nil),    // 4: pb.ItemAttributes
	(*StringAttribute)(nil),   // 5: pb.StringAttribute
	(*StringAttributes)(nil),  // 6: pb.StringAttributes
}
var file_playlist4meta_proto_depIdxs = []int32{
	0, // 0: pb.DownloadFormat.codec:type_name -> pb.DownloadFormat.Codec
	2, // 1: pb.ItemAttributes.download_format:type_name -> pb.DownloadFormat
	5, // 2: pb.StringAttributes.attribute:type_name -> pb.StringAttribute
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_playlist4meta_proto_init() }
func file_playlist4meta_proto_init() {
	if File_playlist4meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_playlist4meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChecksum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playlist4meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadFormat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playlist4meta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playlist4meta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playlist4meta_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playlist4meta_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_playlist4meta_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playlist4meta_proto_goTypes,
		DependencyIndexes: file_playlist4meta_proto_depIdxs,
		EnumInfos:         file_playlist4meta_proto_enumTypes,
		MessageInfos:      file_playlist4meta_proto_msgTypes,
	}.Build()
	File_playlist4meta_proto = out.File
	file_playlist4meta_proto_rawDesc = nil
	file_playlist4meta_proto_goTypes = nil
	file_playlist4meta_proto_depIdxs = nil
}
