// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: playlist4issues.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientIssue_Level int32

const (
	ClientIssue_LEVEL_UNKNOWN ClientIssue_Level = 0
	ClientIssue_LEVEL_DEBUG   ClientIssue_Level = 1
	ClientIssue_LEVEL_INFO    ClientIssue_Level = 2
	ClientIssue_LEVEL_NOTICE  ClientIssue_Level = 3
	ClientIssue_LEVEL_WARNING ClientIssue_Level = 4
	ClientIssue_LEVEL_ERROR   ClientIssue_Level = 5
)

// Enum value maps for ClientIssue_Level.
var (
	ClientIssue_Level_name = map[int32]string{
		0: "LEVEL_UNKNOWN",
		1: "LEVEL_DEBUG",
		2: "LEVEL_INFO",
		3: "LEVEL_NOTICE",
		4: "LEVEL_WARNING",
		5: "LEVEL_ERROR",
	}
	ClientIssue_Level_value = map[string]int32{
		"LEVEL_UNKNOWN": 0,
		"LEVEL_DEBUG":   1,
		"LEVEL_INFO":    2,
		"LEVEL_NOTICE":  3,
		"LEVEL_WARNING": 4,
		"LEVEL_ERROR":   5,
	}
)

func (x ClientIssue_Level) Enum() *ClientIssue_Level {
	p := new(ClientIssue_Level)
	*p = x
	return p
}

func (x ClientIssue_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientIssue_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_playlist4issues_proto_enumTypes[0].Descriptor()
}

func (ClientIssue_Level) Type() protoreflect.EnumType {
	return &file_playlist4issues_proto_enumTypes[0]
}

func (x ClientIssue_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ClientIssue_Level) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ClientIssue_Level(num)
	return nil
}

// Deprecated: Use ClientIssue_Level.Descriptor instead.
func (ClientIssue_Level) EnumDescriptor() ([]byte, []int) {
	return file_playlist4issues_proto_rawDescGZIP(), []int{0, 0}
}

type ClientIssue_Code int32

const (
	ClientIssue_CODE_UNKNOWN             ClientIssue_Code = 0
	ClientIssue_CODE_INDEX_OUT_OF_BOUNDS ClientIssue_Code = 1
	ClientIssue_CODE_VERSION_MISMATCH    ClientIssue_Code = 2
	ClientIssue_CODE_CACHED_CHANGE       ClientIssue_Code = 3
	ClientIssue_CODE_OFFLINE_CHANGE      ClientIssue_Code = 4
	ClientIssue_CODE_CONCURRENT_CHANGE   ClientIssue_Code = 5
)

// Enum value maps for ClientIssue_Code.
var (
	ClientIssue_Code_name = map[int32]string{
		0: "CODE_UNKNOWN",
		1: "CODE_INDEX_OUT_OF_BOUNDS",
		2: "CODE_VERSION_MISMATCH",
		3: "CODE_CACHED_CHANGE",
		4: "CODE_OFFLINE_CHANGE",
		5: "CODE_CONCURRENT_CHANGE",
	}
	ClientIssue_Code_value = map[string]int32{
		"CODE_UNKNOWN":             0,
		"CODE_INDEX_OUT_OF_BOUNDS": 1,
		"CODE_VERSION_MISMATCH":    2,
		"CODE_CACHED_CHANGE":       3,
		"CODE_OFFLINE_CHANGE":      4,
		"CODE_CONCURRENT_CHANGE":   5,
	}
)

func (x ClientIssue_Code) Enum() *ClientIssue_Code {
	p := new(ClientIssue_Code)
	*p = x
	return p
}

func (x ClientIssue_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientIssue_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_playlist4issues_proto_enumTypes[1].Descriptor()
}

func (ClientIssue_Code) Type() protoreflect.EnumType {
	return &file_playlist4issues_proto_enumTypes[1]
}

func (x ClientIssue_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ClientIssue_Code) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ClientIssue_Code(num)
	return nil
}

// Deprecated: Use ClientIssue_Code.Descriptor instead.
func (ClientIssue_Code) EnumDescriptor() ([]byte, []int) {
	return file_playlist4issues_proto_rawDescGZIP(), []int{0, 1}
}

type ClientResolveAction_Code int32

const (
	ClientResolveAction_CODE_UNKNOWN               ClientResolveAction_Code = 0
	ClientResolveAction_CODE_NO_ACTION             ClientResolveAction_Code = 1
	ClientResolveAction_CODE_RETRY                 ClientResolveAction_Code = 2
	ClientResolveAction_CODE_RELOAD                ClientResolveAction_Code = 3
	ClientResolveAction_CODE_DISCARD_LOCAL_CHANGES ClientResolveAction_Code = 4
	ClientResolveAction_CODE_SEND_DUMP             ClientResolveAction_Code = 5
	ClientResolveAction_CODE_DISPLAY_ERROR_MESSAGE ClientResolveAction_Code = 6
)

// Enum value maps for ClientResolveAction_Code.
var (
	ClientResolveAction_Code_name = map[int32]string{
		0: "CODE_UNKNOWN",
		1: "CODE_NO_ACTION",
		2: "CODE_RETRY",
		3: "CODE_RELOAD",
		4: "CODE_DISCARD_LOCAL_CHANGES",
		5: "CODE_SEND_DUMP",
		6: "CODE_DISPLAY_ERROR_MESSAGE",
	}
	ClientResolveAction_Code_value = map[string]int32{
		"CODE_UNKNOWN":               0,
		"CODE_NO_ACTION":             1,
		"CODE_RETRY":                 2,
		"CODE_RELOAD":                3,
		"CODE_DISCARD_LOCAL_CHANGES": 4,
		"CODE_SEND_DUMP":             5,
		"CODE_DISPLAY_ERROR_MESSAGE": 6,
	}
)

func (x ClientResolveAction_Code) Enum() *ClientResolveAction_Code {
	p := new(ClientResolveAction_Code)
	*p = x
	return p
}

func (x ClientResolveAction_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientResolveAction_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_playlist4issues_proto_enumTypes[2].Descriptor()
}

func (ClientResolveAction_Code) Type() protoreflect.EnumType {
	return &file_playlist4issues_proto_enumTypes[2]
}

func (x ClientResolveAction_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ClientResolveAction_Code) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ClientResolveAction_Code(num)
	return nil
}

// Deprecated: Use ClientResolveAction_Code.Descriptor instead.
func (ClientResolveAction_Code) EnumDescriptor() ([]byte, []int) {
	return file_playlist4issues_proto_rawDescGZIP(), []int{1, 0}
}

type ClientResolveAction_Initiator int32

const (
	ClientResolveAction_INITIATOR_UNKNOWN ClientResolveAction_Initiator = 0
	ClientResolveAction_INITIATOR_SERVER  ClientResolveAction_Initiator = 1
	ClientResolveAction_INITIATOR_CLIENT  ClientResolveAction_Initiator = 2
)

// Enum value maps for ClientResolveAction_Initiator.
var (
	ClientResolveAction_Initiator_name = map[int32]string{
		0: "INITIATOR_UNKNOWN",
		1: "INITIATOR_SERVER",
		2: "INITIATOR_CLIENT",
	}
	ClientResolveAction_Initiator_value = map[string]int32{
		"INITIATOR_UNKNOWN": 0,
		"INITIATOR_SERVER":  1,
		"INITIATOR_CLIENT":  2,
	}
)

func (x ClientResolveAction_Initiator) Enum() *ClientResolveAction_Initiator {
	p := new(ClientResolveAction_Initiator)
	*p = x
	return p
}

func (x ClientResolveAction_Initiator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientResolveAction_Initiator) Descriptor() protoreflect.EnumDescriptor {
	return file_playlist4issues_proto_enumTypes[3].Descriptor()
}

func (ClientResolveAction_Initiator) Type() protoreflect.EnumType {
	return &file_playlist4issues_proto_enumTypes[3]
}

func (x ClientResolveAction_Initiator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ClientResolveAction_Initiator) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ClientResolveAction_Initiator(num)
	return nil
}

// Deprecated: Use ClientResolveAction_Initiator.Descriptor instead.
func (ClientResolveAction_Initiator) EnumDescriptor() ([]byte, []int) {
	return file_playlist4issues_proto_rawDescGZIP(), []int{1, 1}
}

type ClientIssue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level       *ClientIssue_Level `protobuf:"varint,1,opt,name=level,enum=pb.ClientIssue_Level" json:"level,omitempty"`
	Code        *ClientIssue_Code  `protobuf:"varint,2,opt,name=code,enum=pb.ClientIssue_Code" json:"code,omitempty"`
	RepeatCount *int32             `protobuf:"varint,3,opt,name=repeatCount" json:"repeatCount,omitempty"`
}

func (x *ClientIssue) Reset() {
	*x = ClientIssue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playlist4issues_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientIssue) ProtoMessage() {}

func (x *ClientIssue) ProtoReflect() protoreflect.Message {
	mi := &file_playlist4issues_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientIssue.ProtoReflect.Descriptor instead.
func (*ClientIssue) Descriptor() ([]byte, []int) {
	return file_playlist4issues_proto_rawDescGZIP(), []int{0}
}

func (x *ClientIssue) GetLevel() ClientIssue_Level {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return ClientIssue_LEVEL_UNKNOWN
}

func (x *ClientIssue) GetCode() ClientIssue_Code {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ClientIssue_CODE_UNKNOWN
}

func (x *ClientIssue) GetRepeatCount() int32 {
	if x != nil && x.RepeatCount != nil {
		return *x.RepeatCount
	}
	return 0
}

type ClientResolveAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      *ClientResolveAction_Code      `protobuf:"varint,1,opt,name=code,enum=pb.ClientResolveAction_Code" json:"code,omitempty"`
	Initiator *ClientResolveAction_Initiator `protobuf:"varint,2,opt,name=initiator,enum=pb.ClientResolveAction_Initiator" json:"initiator,omitempty"`
}

func (x *ClientResolveAction) Reset() {
	*x = ClientResolveAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playlist4issues_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientResolveAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResolveAction) ProtoMessage() {}

func (x *ClientResolveAction) ProtoReflect() protoreflect.Message {
	mi := &file_playlist4issues_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResolveAction.ProtoReflect.Descriptor instead.
func (*ClientResolveAction) Descriptor() ([]byte, []int) {
	return file_playlist4issues_proto_rawDescGZIP(), []int{1}
}

func (x *ClientResolveAction) GetCode() ClientResolveAction_Code {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ClientResolveAction_CODE_UNKNOWN
}

func (x *ClientResolveAction) GetInitiator() ClientResolveAction_Initiator {
	if x != nil && x.Initiator != nil {
		return *x.Initiator
	}
	return ClientResolveAction_INITIATOR_UNKNOWN
}

var File_playlist4issues_proto protoreflect.FileDescriptor

var file_playlist4issues_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x34, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x9a, 0x03, 0x0a, 0x0b,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x28, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x71, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x11, 0x0a,
	0x0d, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x44, 0x45, 0x42, 0x55, 0x47, 0x10,
	0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10,
	0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43,
	0x45, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x57, 0x41, 0x52,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x05, 0x22, 0x9e, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x49, 0x4e, 0x44, 0x45, 0x58,
	0x5f, 0x4f, 0x55, 0x54, 0x5f, 0x4f, 0x46, 0x5f, 0x42, 0x4f, 0x55, 0x4e, 0x44, 0x53, 0x10, 0x01,
	0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e,
	0x5f, 0x4d, 0x49, 0x53, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x43,
	0x4f, 0x44, 0x45, 0x5f, 0x43, 0x41, 0x43, 0x48, 0x45, 0x44, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47,
	0x45, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4f, 0x46, 0x46, 0x4c,
	0x49, 0x4e, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x54, 0x5f,
	0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x05, 0x22, 0xfc, 0x02, 0x0a, 0x13, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x30, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x74, 0x6f, 0x72, 0x22, 0xa1, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x0c,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12,
	0x0a, 0x0e, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x52, 0x45, 0x54, 0x52, 0x59,
	0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x52, 0x45, 0x4c, 0x4f, 0x41,
	0x44, 0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x44, 0x49, 0x53, 0x43,
	0x41, 0x52, 0x44, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45,
	0x53, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x53, 0x45, 0x4e, 0x44,
	0x5f, 0x44, 0x55, 0x4d, 0x50, 0x10, 0x05, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x44, 0x45, 0x5f,
	0x44, 0x49, 0x53, 0x50, 0x4c, 0x41, 0x59, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x4d, 0x45,
	0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x06, 0x22, 0x4e, 0x0a, 0x09, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x54, 0x4f,
	0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x49,
	0x4e, 0x49, 0x54, 0x49, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10,
	0x01, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x43,
	0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x62,
}

var (
	file_playlist4issues_proto_rawDescOnce sync.Once
	file_playlist4issues_proto_rawDescData = file_playlist4issues_proto_rawDesc
)

func file_playlist4issues_proto_rawDescGZIP() []byte {
	file_playlist4issues_proto_rawDescOnce.Do(func() {
		file_playlist4issues_proto_rawDescData = protoimpl.X.CompressGZIP(file_playlist4issues_proto_rawDescData)
	})
	return file_playlist4issues_proto_rawDescData
}

var file_playlist4issues_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_playlist4issues_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_playlist4issues_proto_goTypes = []interface{}{
	(ClientIssue_Level)(0),             // 0: pb.ClientIssue.Level
	(ClientIssue_Code)(0),              // 1: pb.ClientIssue.Code
	(ClientResolveAction_Code)(0),      // 2: pb.ClientResolveAction.Code
	(ClientResolveAction_Initiator)(0), // 3: pb.ClientResolveAction.Initiator
	(*ClientIssue)(nil),                // 4: pb.ClientIssue
	(*ClientResolveAction)(nil),        // 5: pb.ClientResolveAction
}
var file_playlist4issues_proto_depIdxs = []int32{
	0, // 0: pb.ClientIssue.level:type_name -> pb.ClientIssue.Level
	1, // 1: pb.ClientIssue.code:type_name -> pb.ClientIssue.Code
	2, // 2: pb.ClientResolveAction.code:type_name -> pb.ClientResolveAction.Code
	3, // 3: pb.ClientResolveAction.initiator:type_name -> pb.ClientResolveAction.Initiator
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_playlist4issues_proto_init() }
func file_playlist4issues_proto_init() {
	if File_playlist4issues_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_playlist4issues_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientIssue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playlist4issues_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientResolveAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_playlist4issues_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playlist4issues_proto_goTypes,
		DependencyIndexes: file_playlist4issues_proto_depIdxs,
		EnumInfos:         file_playlist4issues_proto_enumTypes,
		MessageInfos:      file_playlist4issues_proto_msgTypes,
	}.Build()
	File_playlist4issues_proto = out.File
	file_playlist4issues_proto_rawDesc = nil
	file_playlist4issues_proto_goTypes = nil
	file_playlist4issues_proto_depIdxs = nil
}
